# Generated by Django 2.2.5 on 2019-09-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('issue_a', models.CharField(max_length=100)),
                ('issue_b', models.CharField(max_length=100)),
                ('image_a', models.ImageField(blank=True, upload_to='')),
                ('image_b', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
